name: rpi_health Action

on: [push]

jobs:

  build:  # A job in the workflow called "build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}  # First task to run.
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox-gh-actions
        pip install -r requirements.txt

    - name: Run tox
      run: |
        tox
